"""for persosns table add created_at, updated_at columns

Revision ID: c9f35402648f
Revises: 3ad18bf7ccac
Create Date: 2025-09-07 21:18:30.041837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f35402648f'
down_revision: Union[str, Sequence[str], None] = '3ad18bf7ccac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('persons', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'updated_at')
    op.drop_column('persons', 'created_at')
    # ### end Alembic commands ###
